### ISSUE TITLE
srv1 testing

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-srv1#4]
Please build and test the code in this repo as per the instructions in the readme file, please take note of missing steps or whenever you get stuck.

**Comment by mohammedbakr** [comment]
After building the image and running RabbitMQ and MinIO containers
I got connection refused when running this command:
`docker run -e ADAPTATION_REQUEST_QUEUE_HOSTNAME='<rabbit-host>' \ 
-e ADAPTATION_REQUEST_QUEUE_PORT='<rabbit-port>' \
-e MESSAGE_BROKER_USER='<rabbit-user>' \
-e MESSAGE_BROKER_PASSWORD='<rabbit-password>' \
-e MINIO_ENDPOINT='<minio-endpoint>' \ 
-e MINIO_ACCESS_KEY='<minio-access>' \ 
-e MINIO_SECRET_KEY='<minio-secret>' \ 
-e MINIO_SOURCE_BUCKET='<bucket-to-upload-file>' \ 
--name <docker_container_name> <docker_image_name>`
after changing the variables like illustrated in the attached image.
[
![ref](https://user-images.githubusercontent.com/53897706/112452457-4f7e0300-8d5f-11eb-90c5-796433337659.PNG)
](url)

**Comment by mahnouman** [comment]
Hello @azopat the first round of test was not successful, please check the test report from @mohammedbakr , it is the comment above and amend the instructions accordingly, thank you.

**Comment by azopat** [comment]
@mohammedbakr 
you are trying to contact host network from a docker machine. instead you use use rabbit mq internal network address

**Comment by mohammedbakr** [comment]
Illustrate more with the right running commands of MinIO and RabbitMQ, please
